#!/bin/bash

# Recompile ramulator
make -j8

ramulator/ramulator configs/baseline.cfg --mode=cpu --stats output/gcc.stats traces/gcc.trace
ramulator/ramulator configs/baseline.cfg --mode=cpu --stats output/mcf.stats traces/mcf.trace
ramulator/ramulator configs/baseline.cfg --mode=cpu --stats output/milc.stats traces/milc.trace
ramulator/ramulator configs/baseline.cfg --mode=cpu --stats output/omnetpp.stats traces/omnetpp.trace

ramulator/ramulator configs/baseline.cfg --mode=cpu --stats output/baseline_shared.stats traces/gcc.trace traces/mcf.trace traces/milc.trace traces/omnetpp.trace

# Waypart
ramulator/ramulator configs/waypart.cfg --mode=cpu --stats output/waypart.stats traces/gcc.trace traces/mcf.trace traces/milc.trace traces/omnetpp.trace

# BLISS
ramulator/ramulator configs/bliss.cfg --mode=cpu --stats output/bliss.stats traces/gcc.trace traces/mcf.trace traces/milc.trace traces/omnetpp.trace